### PR TITLE
Update TranslationFileRewriter.php

### PR DESCRIPTION
**Pull request by bsormagec**
Fixed Countable Error

### CODE REVIEW

**Comment by bsormagec** [comment]
@vsch can you merge that fix i cant publish changes on my project that change fixing problem. Thanks.

**Comment by vsch** [comment]
@bsormagec , thank you for the fix.

**Comment by vsch** [comment]
@bsormagec, new release now available.

**Comment by bsormagec** [comment]
Thank you @vsch

**Comment by vsch** [comment]
@bsormagec, You are welcome.

**Pull request merged**
