### PR TITLE
add database layer

### PR DESCRIPTION
**Pull request by al0mie**
I guess it's more preferable to move all work with db in some abstract layer. I created a repository for this and inject it in controller and manager via standart IoC, and move there most sql queries. It's seems that controller and manager have become more clean and also don't duplicate sql queries. What do you think?

### CODE REVIEW

**Comment by al0mie** [comment]
Also it required some refactoring there

**Comment by vsch** [comment]
@al0mie, that's awesome. Thank you.

**Comment by al0mie** [comment]
@vsch, mm I think it's early to do release. I test more and do refactoring later. Write if will found bugs.

**Comment by vsch** [comment]
@al0mie, I had this from the beginning as a todo item (#4) but waited to see if there is a demand but never got any until #66. Thank you for taking the initiative. Much appreciated.

**Comment by vsch** [comment]
@al0mie, I'll run my dev environment with it and release the last PR's after some confidence in the changes.

**Comment by al0mie** [comment]
@vsch, You are welcome. I tried run unit tests, but seems that something wrong http://prnt.sc/edmax4 . Also I think better to do something more abstract with db and rewrite heredoc to raw query builder. That will add support not only for mysql

**Comment by vsch** [comment]
@al0mie, I am now refactoring the remaining SQL in Controller.php. It is still in its original hacked version with no comments so I need to figure it out. 😊 

After all SQL is moved out then the next step of converting to raw query builder can be addressed. Maybe a better option is to refactor query builder based queries as a base class with DB specific derived classes overriding the query builder with queries targeting a specific SQL dialect.  This will give the best of both worlds when needed.

I use remote connections to my AWS instances and without reducing number round trips performance was intolerable. I tried to optimize DB access specifically for remote DB connections where each round trip is huge penalty in performance. 

I have not run tests in a while because some changes out-dated them. I will update these.

**Comment by al0mie** [comment]
>> It is still in its original hacked version with no comments so I need to figure it out.

Yes. I really do not understand them so didn't touch.

>> Maybe a better option is to refactor query builder based queries as a base class with DB specific derived classes overriding the query builder with queries targeting a specific SQL dialect. This will give the best of both worlds when needed.

Why not simple use https://laravel.com/docs/5.4/queries#raw-expressions? If you specific for each database, specific class, it will not be extra duplicated code? Also you need be really good for all dialects (mysql, postresql, sqlite at least), any mistakes will easy bring some bugs and that hard to detect them. Without good unit tests, of course.

**Comment by vsch** [comment]
@al0mie, what I had in mind for specific dialects is for all dialects to use inherited query builder versions and in those cases where a more efficient version can be written for a specific method for a specific database then this is an option with a method override.

I have not done DB centric development for almost a decade so don't consider myself an expert. 10 years without use is enough to forget your mother tongue much less nuances SQL. I only get to it when performance is so crappy that I can't take it and dive into query analysis and optimization.

I would not handle other dialects and would leave that for users who use that dialect and have a better way of doing it to contribute the dialect specific change.

**Comment by al0mie** [comment]
@vsch Yes, I understood you. I guess it will be nice to specify one more layer for it and to inject in repository. Or specific interface and to bind with realization in depend of config file. Something like 
>> App::bind('UserRepositoryInterface', 'DbUserRepository');

Where implementation will be that extended classes.
And that not require to refactor code, which already in Manager or Controller (there will call a method from TranslatorRepository) 
Maybe will do it myself sometime.

**Pull request merged**
