### PR TITLE
update web interface for ru local

### PR DESCRIPTION
**Pull request by al0mie**
Maybe it's clearer?

### CODE REVIEW

**Comment by vsch** [comment]
@al0mie, спасибо. Так как я родился в СССР и закончил 3 класса образования до иммиграции в Канаду через Израиль и Австрию, я еще не плохо справляюсь с русским в беседе. Переводить и писать мне на много труднее, особенно в технической сфере.

**Comment by al0mie** [comment]
@vsch, не за что. Там было бы не плохо сделать более понятный перевод для русского языка. В будующем постараюсь это сделать (пока я не полностью понимаю какие ключи где используются).

**Comment by vsch** [comment]
@al0mie, if you switch the WebUI to "Edit In Place", select Interface language as RU and LTM messages group (may show up different on your system since on my dev system I have LTM in workbench which is a left-over from Laravel 4 convention) then you will be able to click on the translations. I highlighted these controls in red.

Some hidden translations are also shown these are used for disabled button text. I highlighted one in blue and put arrows to some of the others.

I did not highlight the translations for alerts that pop up but these are in the top left corner of the page.

The translations that start with "title-" are translation passed to JS for tooltip (title attribute) of edit pop-up.

screen shot 2017-02-16 at 1 56 10 pm

**Comment by al0mie** [comment]
@vsch, Thanks, I'll look next time. So rich interface some confused in the first time. Maybe also some styles will try change for more adaptivity.

**Comment by vsch** [comment]
@al0mie, not really intended to be used except in extreme circumstances when you need to locate a translation. Easier than looking through the code. Each element just dumps translations it uses in the same area as the location of the element.

I agree it would be better to have an interface for each element which allowed you to see the translation this element uses. However, this would require much more work, I simply used the "contractor special" to get the minimal functionality that allowed me to solve an immediate problem. Haven't really gone back.

The other in place edit option lists the translations but also suffers from not being able to connect the translation to where it is being used. The above dump lets you see that where the translation is being used "most of the time" by the vicinity of the link and the element using the translation.

I am open to any suggestions you have regarding improving this.

**Pull request merged**
