### PR TITLE
Support Laravel 5.2

### PR DESCRIPTION
**Pull request by killtw**

### CODE REVIEW

**Comment by vsch** [comment]
@killtw, thanks.

**Comment by killtw** [comment]
@vsch don't forget update your packagist.

**Comment by vsch** [comment]
@killtw, I will do it today. Thanks.

**Comment by vsch** [comment]
@killtw, done. Thank you for the update to Laravel 5.2. I have been busy with a [Markdown plugin for IntelliJ IDEs](https://github.com/vsch/idea-multimarkdown) lately and spent little time on anything else. I wish there were more hours in a day or I could get by with less than 5 hours of sleep. :)

**Comment by killtw** [comment]
@vsch you should take more sleep, health is the most important thing than anything

**Comment by vsch** [comment]
I agree but "publish or perish" is not just for tenured university professors. I spent 25+ years in offices as a consultant and got tired of corporate politics and middle management incompetence. I left the field for 6 years. Missed the joy of development too much and decided to get back in about a year ago. 

Now I want to get to a point where I can make a living being an independent developer.

**Comment by jfeid** [comment]
Any chance to continue support L5.2?

Currently I have found issues #98 & #27 still exist on L5.2

**Comment by vsch** [comment]
@jfeid, keeping multiple versions in sync is getting more difficult the further back in time I go.

It is complicated by my lack of available time and the fact that I no longer have working environments in which to test earlier versions. Making changes and not being able to validate that they work in not a good idea.

I don't remember details of the changes from 5.2 to 5.3 but suspect that the version for 5.3 would probably work with Laravel 5.2 with only the laravel version change in composer.json.

If you try it and find that it is working with Laravel 5.2 then I can take 5.3 branch, change composer.json Laravel versions and make a new release for 5.2. At least that way it will be up to date with 5.3.

**Pull request merged**
